
const TA_ROLE_TYPE = 1;
const PROFESSOR_ROLE_TYPE = 2;
const ADMIN_ROLE_TYPE = 3 ;


exports.TA_ROLE_TYPE = TA_ROLE_TYPE;
exports.PROFESSOR_ROLE_TYPE = PROFESSOR_ROLE_TYPE;
exports.ADMIN_ROLE_TYPE = ADMIN_ROLE_TYPE;

